### ISSUE TITLE
seata使用例子可以随之更新吗？

### ISSUE THREAD

**Issue by ListenQ** [apache/incubator-seata-samples#648]
采用seata + springboot + dubbo + mybatis + nacos 的例子，可以更新一下吗？
目前是2019年的老旧版本，随着发布更新一起升级调整下例子就好

期望
seata version：2.0.0
springboot version：2.7.x 及以上
dubbo version：3.1.0 +

**Comment by ptyin** [comment]
We have recently refactored the sample repository by apache/incubator-seata-samples#647.

You can check it [here](https://github.com/apache/incubator-seata-samples/tree/master/at-sample/springboot-dubbo-seata) to see if that satisfies your requirements.

**Comment by ListenQ** [comment]
Okay, thanks.

**Comment by ListenQ** [comment]
- 官方文档地址这里：https://seata.apache.org/zh-cn/docs/user/quickstart/   可以跟新一下吗？
- https://github.com/apache/incubator-seata-samples/tree/master/at-sample/springboot-dubbo-seata 这里没有找到demo test相关信息

**Comment by ptyin** [comment]
> * 官方文档地址这里：https://seata.apache.org/zh-cn/docs/user/quickstart/   可以跟新一下吗？

Sure. I will fix that.

> * https://github.com/apache/incubator-seata-samples/tree/master/at-sample/springboot-dubbo-seata 这里没有找到demo test相关信息

Run this [file](https://github.com/apache/incubator-seata-samples/blob/master/at-sample/springboot-dubbo-seata/springboot-dubbo-seata-business/src/main/java/org/apache/seata/SpringbootDubboSeataBusinessApplication.java).

**Comment by ListenQ** [comment]
1. TC（seata server端）设计及原理可以详细出文档说说吗？
启动 seata server ，开启mysql log 查看如下图，会一直频繁的刷是什么？
![image](https://github.com/apache/incubator-seata-samples/assets/28863941/1829985e-b933-4b87-8c4c-e14a34dcebaa)

2. TC 管理界面一直显示信息是为哈？什么原因？
![image](https://github.com/apache/incubator-seata-samples/assets/28863941/37e2a445-4c70-4059-b61b-c392ff65c45d)
![image](https://github.com/apache/incubator-seata-samples/assets/28863941/b4e16b73-9374-4766-b1c9-1f25b982b212)

**Comment by ptyin** [comment]
For implementation, you can
- refer to [dev docs](https://seata.apache.org/zh-cn/docs/next/dev/mode/at-mode/) for AT implementation details.
- check [blog](https://seata.apache.org/zh-cn/blog) to search for relevant resources.

I will close this issue. For any unexpected behaviour of Seata, please open a new issue in the [main repository](https://github.com/apache/incubator-seata/issues/new/choose) and supplement related error logs and version information.
