### ISSUE TITLE
codeQL workflow failed

### ISSUE THREAD

**Issue by slievrly** [apache/incubator-seata-samples#672]
- [ ] I have searched the [issues](https://github.com/apache/incubator-seata-samples/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

![image](https://github.com/apache/incubator-seata-samples/assets/8758457/a7cb2bde-2257-4e42-a3c7-ce7cb9b40960)
https://github.com/apache/incubator-seata-samples/actions/runs/8864796595/job/24340345848

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by ptyin** [comment]
#660

**Comment by slievrly** [comment]
resolved #660
